name: Semgrep

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    uses: pcvantol/djconnect/.github/workflows/djconnect-semgrep-ci.yml@main
